### ISSUE TITLE
precision is variable

### ISSUE THREAD

**Issue by rjbs** [ikegami/perl-DateTime-Format-RFC3339#3]
This appears in the source:
```perl
      $dt->strftime(
         ($dt->nanosecond()
            ? '%Y-%m-%dT%H:%M:%S.%9N'
            : '%Y-%m-%dT%H:%M:%S'
         )
      ).$tz;
```

This means that precision is tied to the value of nanosecond, which can actually be zero.  This will be a rare event (say, one in a million for someone using `gettimeofday`) but "any time you make a time string" happens often.

It should be possible to specify that subsecond resolution is always required, which would ensure a constant width of output.  (Being able to specify the width would be nice, too.)

In fact, moving that to the object would eliminate one method call (to $dt->nanosecond) for every object formatted.

**Comment by ikegami** [comment]
I agree. I have another change to add customizability I need to make this module. If there's no rush, I'll get to it in under a week.

**Comment by ikegami** [comment]
@rjbs Any suggestion as to how to handle rounding (floor, ceil, round, configurable)?

**Comment by ikegami** [comment]
> @rjbs Any suggestion as to how to handle rounding (floor, ceil, round, configurable)?

Whatever DT already does, duh.

**Comment by rjbs** [comment]
No rush!  It was easy to just throw some sprintf at my problem, which has now been solved until some future date, but it felt like I should send this feedback rather than drop it in the bitbucket!  Thanks.

**Comment by ikegami** [comment]
Option added to v1.4.0
